# Generated by Django 4.2.4 on 2023-10-09 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_alter_film_options_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='text_revievs',
            new_name='text_reviews',
        ),
    ]
